// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: ram.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RAM_RAMType int32

const (
	RAM_UNKNOWN RAM_RAMType = 0
	RAM_DDR3    RAM_RAMType = 1
	RAM_DDR4    RAM_RAMType = 2
	RAM_DDR5    RAM_RAMType = 3
)

// Enum value maps for RAM_RAMType.
var (
	RAM_RAMType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DDR3",
		2: "DDR4",
		3: "DDR5",
	}
	RAM_RAMType_value = map[string]int32{
		"UNKNOWN": 0,
		"DDR3":    1,
		"DDR4":    2,
		"DDR5":    3,
	}
)

func (x RAM_RAMType) Enum() *RAM_RAMType {
	p := new(RAM_RAMType)
	*p = x
	return p
}

func (x RAM_RAMType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RAM_RAMType) Descriptor() protoreflect.EnumDescriptor {
	return file_ram_proto_enumTypes[0].Descriptor()
}

func (RAM_RAMType) Type() protoreflect.EnumType {
	return &file_ram_proto_enumTypes[0]
}

func (x RAM_RAMType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RAM_RAMType.Descriptor instead.
func (RAM_RAMType) EnumDescriptor() ([]byte, []int) {
	return file_ram_proto_rawDescGZIP(), []int{0, 0}
}

type RAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RamType RAM_RAMType `protobuf:"varint,1,opt,name=ram_type,json=ramType,proto3,enum=pcbook.RAM_RAMType" json:"ram_type,omitempty"`
	Memory  *Memory     `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *RAM) Reset() {
	*x = RAM{}
	mi := &file_ram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAM) ProtoMessage() {}

func (x *RAM) ProtoReflect() protoreflect.Message {
	mi := &file_ram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAM.ProtoReflect.Descriptor instead.
func (*RAM) Descriptor() ([]byte, []int) {
	return file_ram_proto_rawDescGZIP(), []int{0}
}

func (x *RAM) GetRamType() RAM_RAMType {
	if x != nil {
		return x.RamType
	}
	return RAM_UNKNOWN
}

func (x *RAM) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_ram_proto protoreflect.FileDescriptor

var file_ram_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x63, 0x62,
	0x6f, 0x6f, 0x6b, 0x1a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x93, 0x01, 0x0a, 0x03, 0x52, 0x41, 0x4d, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x61, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x63,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x52, 0x41, 0x4d, 0x2e, 0x52, 0x41, 0x4d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x07, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x63, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x22, 0x34, 0x0a, 0x07, 0x52, 0x41, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x44, 0x52,
	0x33, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x44, 0x52, 0x34, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x44, 0x52, 0x35, 0x10, 0x03, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x61,
	0x76, 0x32, 0x30, 0x2f, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ram_proto_rawDescOnce sync.Once
	file_ram_proto_rawDescData = file_ram_proto_rawDesc
)

func file_ram_proto_rawDescGZIP() []byte {
	file_ram_proto_rawDescOnce.Do(func() {
		file_ram_proto_rawDescData = protoimpl.X.CompressGZIP(file_ram_proto_rawDescData)
	})
	return file_ram_proto_rawDescData
}

var file_ram_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ram_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ram_proto_goTypes = []any{
	(RAM_RAMType)(0), // 0: pcbook.RAM.RAMType
	(*RAM)(nil),      // 1: pcbook.RAM
	(*Memory)(nil),   // 2: pcbook.Memory
}
var file_ram_proto_depIdxs = []int32{
	0, // 0: pcbook.RAM.ram_type:type_name -> pcbook.RAM.RAMType
	2, // 1: pcbook.RAM.memory:type_name -> pcbook.Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ram_proto_init() }
func file_ram_proto_init() {
	if File_ram_proto != nil {
		return
	}
	file_memory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ram_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ram_proto_goTypes,
		DependencyIndexes: file_ram_proto_depIdxs,
		EnumInfos:         file_ram_proto_enumTypes,
		MessageInfos:      file_ram_proto_msgTypes,
	}.Build()
	File_ram_proto = out.File
	file_ram_proto_rawDesc = nil
	file_ram_proto_goTypes = nil
	file_ram_proto_depIdxs = nil
}
